name       : openjfx-8
version    : '8.201'
release    : 7
source     :
    - https://hg.openjdk.java.net/openjfx/8u-dev/rt/archive/8u201-ga.tar.bz2 : a5f69e13deaf36002ab597e3e630fd4e3a7162755245a8762e1a6e5a6e75b848
license    : GPL-2.0-or-later WITH Classpath-exception-2.0
component  : programming.java
summary    : OpenJFX is an open source, next generation client application platform for desktop and embedded systems based on JavaSE
description: |
    OpenJFX is an open source, next generation client application platform for desktop and embedded systems based on JavaSE
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(Qt5Core)
    - pkgconfig(ruby-2.6)
    - pkgconfig(xtst)
    - gperf
    - gradle
    - openjdk-8-devel
rundeps    :
    - openjdk-8
networking : yes
setup      : |
    cp $pkgfiles/gradle.properties .
    %patch -p1 < $pkgfiles/0001-GCC6-fix.patch
    %patch -p1 < $pkgfiles/0002-Fix-build-errors.patch
    %patch -p1 < $pkgfiles/0003-Disable-compiler-errors.patch
build      : |
    export GRADLE_USER_HOME=$workdir
    gradle --no-daemon --stacktrace
install    : |
    install -Dm00755 build/sdk/bin/* -t $installdir/usr/lib64/openjdk-8/bin

    install -dm00755 $installdir/usr/lib64/openjdk-8/jre
    cp -a build/sdk/rt/lib $installdir/usr/lib64/openjdk-8/jre
    cp -a build/sdk/lib $installdir/usr/lib64/openjdk-8

    # Sort out the manpages (with a "-8" suffix)
    install -dm00755 $installdir/usr/share
    cp -a build/sdk/man $installdir/usr/share
    mv $installdir/usr/share/man/ja_JP.UTF-8 $installdir/usr/share/man/ja
    find $installdir/usr/share/man -type f -exec rename -- .1 -8.1 {} \;
