name       : openjfx-8
version    : '8.172'
release    : 2
source     :
    - http://hg.openjdk.java.net/openjfx/8u-dev/rt/archive/2991e8b097f3.tar.bz2 : 9d63ed315949362bbb14020c2e0251a872640e43b33d2a60982c0d815190a93b
license    : GPL-2.0
component  : programming.java
summary    : OpenJFX is an open source, next generation client application platform for desktop and embedded systems based on JavaSE
description: |
    OpenJFX is an open source, next generation client application platform for desktop and embedded systems based on JavaSE
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Core)
    - pkgconfig(ruby-2.3)
    - pkgconfig(xtst)
    - gperf
    - gradle
    - openjdk-8-devel
rundeps    :
    - openjdk-8
networking : yes
setup      : |
    cp $pkgfiles/gradle.properties .
    %patch -p1 < $pkgfiles/gcc6.patch
build      : |
    export GRADLE_USER_HOME=$workdir
    gradle --no-daemon --stacktrace
install    : |
    install -d $installdir/usr/lib64/openjdk-8/bin
    install -m 00755 build/sdk/bin/* $installdir/usr/lib64/openjdk-8/bin

    install -d $installdir/usr/lib64/openjdk-8/jre/lib/{amd64,ext}
    install -m 00755 build/sdk/rt/lib/amd64/* $installdir/usr/lib64/openjdk-8/jre/lib/amd64
    install -m 00644 build/sdk/rt/lib/ext/* $installdir/usr/lib64/openjdk-8/jre/lib/ext
    install -m 00644 build/sdk/rt/lib/*.* $installdir/usr/lib64/openjdk-8/jre/lib

    install -d $installdir/usr/lib64/openjdk-8/lib
    install -m 00644 build/sdk/lib/* $installdir/usr/lib64/openjdk-8/lib

    install -d $installdir/usr/share/man/man1
    install -m 00644 build/sdk/man/man1/* $installdir/usr/share/man/man1
