name       : openjfx-8
version    : '8.202'
release    : 8
source     :
    - https://hg.openjdk.java.net/openjfx/8u-dev/rt/archive/8u202-ga.tar.bz2 : 12b0538d04c4bd451e4692ee06357ac36233ff4ec2af9fa3b9bbdbab48c3f2fc
license    : GPL-2.0-or-later WITH Classpath-exception-2.0
component  : programming.java
homepage   : https://openjfx.io/
summary    : Open source client application platform for desktop and embedded systems based on Java
description: |
    JavaFX is an open source, next generation client application platform for desktop, mobile and embedded systems built on Java. It is a collaborative effort by many individuals and companies with the goal of producing a modern, efficient, and fully featured toolkit for developing rich client applications.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(ruby-2.7)
    - pkgconfig(xtst)
    - pkgconfig(xxf86vm)
    - gperf
    - openjdk-8-devel
rundeps    :
    - openjdk-8
networking : yes
setup      : |
    cp $pkgfiles/gradle.properties .
    %apply_patches
    chmod +x gradlew
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-8
    export GRADLE_USER_HOME=$workdir/.gradle_home

    ./gradlew --no-daemon --stacktrace
install    : |
    install -Dm00755 build/sdk/bin/* -t $installdir/usr/lib64/openjdk-8/bin

    install -dm00755 $installdir/usr/lib64/openjdk-8/jre
    cp -a build/sdk/rt/lib $installdir/usr/lib64/openjdk-8/jre
    cp -a build/sdk/lib $installdir/usr/lib64/openjdk-8

    # Sort out the manpages (with a "-8" suffix)
    install -dm00755 $installdir/usr/share
    cp -a build/sdk/man $installdir/usr/share
    mv $installdir/usr/share/man/ja_JP.UTF-8 $installdir/usr/share/man/ja
    find $installdir/usr/share/man -type f -exec rename -- .1 -8.1 {} \;
